### ISSUE TITLE
Armorstand wont display wings from Botania

### ISSUE THREAD

**Issue by StarStorms21** [ochotonida/curious-armor-stands#10]
Item affected
![image](https://github.com/ochotonida/curious-armor-stands/assets/41026702/95f1c9c3-085b-4bc8-b0ee-cd5156d1723f)

Armor stand with item (nothing happens):
![image](https://github.com/ochotonida/curious-armor-stands/assets/41026702/41d91b1b-c095-4bc3-8de9-36d61c4b713d)

How its supposed to look:
![image](https://github.com/ochotonida/curious-armor-stands/assets/41026702/35223816-9911-4fa6-bc87-22517e270ada)

Im not sure if this is an issue of this mod or botania, but I thought id let you know!

Using custom texturepack that changes the sprite of the wings, but it doesn't work on default textures either.

Versions:
Minecraft Forge: 1.20.1 - 47.2.17
Curios API: 5.9.1+1.20.1
Curious Armorstands: 1.20-5.1.0
Botania: 1.20.1-444-forge

**Comment by ochotonida** [comment]
Thanks for the report! Unfortunately this is something that would have to be fixed on Botania's end. They specifically check whether an entity is a player before rendering the item. I can't really find a good reason why it's like this though, so it wouldn't hurt to report it to them.
https://github.com/VazkiiMods/Botania/blob/ec7870b8fec5066865e55730cb97a00a974affde/Xplat/src/main/java/vazkii/botania/common/item/equipment/bauble/FlugelTiaraItem.java#L279
