### ISSUE TITLE
Crash with newer betas of Curios

### ISSUE THREAD

**Issue by brisingraerowing** [ochotonida/curious-armor-stands#5]
[Crash Log](https://gist.github.com/brisingraerowing/9e73201cb757e5c59ad896c27a338ffd)

(The Lightman's Currency stuff is from the Armor Trader, which places an armor stand when placed).

It looks like some API stuff has changed.

**Comment by ochotonida** [comment]
Version 1.16.5-2.2.0 should fix this, you probably missed it because I initially marked it as beta on curseforge (It seems the curseforge launcher doesn't always download those). I've changed the Release Type from Beta to Release to avoid this issue, thanks for letting me know.
