### ISSUE TITLE
Crash upon trying to place armor stand

### ISSUE THREAD

**Issue by DWX12** [ochotonida/curious-armor-stands#6]
Minecraft - 1.18.2
Forge - 40.1.42
Curious Armor Stands - curious-armor-stands-1.18.1-4.0.0

Playing in single player. When I attempted to place an armor stand, Minecraft crashed.

Crash report -
https://www.toptal.com/developers/hastebin/kizemosose.properties

**Comment by ochotonida** [comment]
I haven't been able to reproduce this issue so far, so I'll be closing it for now. If anyone is still having this problem feel free to open a new issue.
