### ISSUE TITLE
Items fall off armor stands on loading world (Singleplayer)

### ISSUE THREAD

**Issue by Terra-B-Welch** [ochotonida/curious-armor-stands#8]
Versions:
--- Minecraft: 1.20.1
--- Curios: 5.8.1
--- Curious Armor Stands: 5.0.1
--- Forge/Fabric: Forge 47.2.20

Observed Behavior:
Upon loading a world, curios on armor stands(namely tested with artifacts mod) seem to fall off their armor stands the next time the world is loaded in(Save and Quit, then load the same world), no logs of note are shown when looking at the logs.

Items can be placed back on the armor stands, but will fall off again the next time the world is loaded again, it's more an annoyance if anything.

**Comment by ochotonida** [comment]
This appears to be caused by a recent Curios update, I'm not sure if there's anything I can do to fix this from my end. Downgrading Curios to 5.7.2 should fix it for now.

**Comment by ghost** [comment]
I wanted to use the simple hats mod so I updated curios, guess I'm just going to have to deal with it :s

**Comment by ochotonida** [comment]
Curios just released an update that fixes this issue.
