### ISSUE TITLE
[1.20.1] Incompatiblity with Spyglass of Curios

### ISSUE THREAD

**Issue by infinitephantasm** [ochotonida/curious-armor-stands#9]
Attempting to place a spyglass on an armor stand with [Spyglass of Curios](https://modrinth.com/mod/spyglass-of-curios/) installed results in a crash that is impossible to recover from without editing the world to remove the armor stand, or removing Curious Armor Stands entirely (at the cost of removing any Curios placed onto the stand). Rejoining the world without doing so will crash you again.

Running NeoForge 47.1.105 on Minecraft version 1.20.1, Curios API version 5.9.1, Curious Armor Stands version 5.1.0.

EDIT: In my haste to submit this, I forgot to add a crash report. [Here's one.](https://pst.innomi.net/paste/nztyhxm3u69tako6485t4xmt)

**Comment by ochotonida** [comment]
This is an issue with Spyglass of Curios' rendering code, it will have to be fixed on their end.
